<script setup lang="ts">
import { onMounted, ref } from "vue";
import { listPresetApps, pickCustomApp, saveMappingConfiguration, upsertApplicationBinding, removeApplicationBinding, type ApplicationBinding, type MappingConfiguration, type PresetAppInfo } from "../lib/bridge";
const props = defineProps<{ configuration: MappingConfiguration }>();
const emit = defineEmits<{ saved: [configuration: MappingConfiguration] }>();
const apps = ref<PresetAppInfo[]>([]); const error = ref<string | null>(null); const busy = ref(false);
onMounted(async()=>{ apps.value=await listPresetApps(); });
async function bind(applicationId:string, templateId:string) { if(!templateId) return; busy.value=true; error.value=null; try { emit("saved",await upsertApplicationBinding({applicationId,templateId,menuOrder:props.configuration.applicationBindings.length})); } catch(e){error.value=String(e)} finally{busy.value=false} }
async function unbind(applicationId:string){busy.value=true;try{emit("saved",await removeApplicationBinding(applicationId))}catch(e){error.value=String(e)}finally{busy.value=false}}
async function custom(){const app=await pickCustomApp();if(app) apps.value.push({id:app.path,name:app.name,installed:true});}
function binding(id:string):ApplicationBinding|undefined{return props.configuration.applicationBindings.find(x=>x.applicationId===id)}
function orderedBindings() { return [...props.configuration.applicationBindings].sort((a,b)=>a.menuOrder-b.menuOrder); }
async function move(applicationId:string, direction:number) { const items=orderedBindings(); const index=items.findIndex(x=>x.applicationId===applicationId); const next=index+direction; if(next<0||next>=items.length)return; const reordered=[...items]; [reordered[index],reordered[next]]=[reordered[next],reordered[index]]; const bindings=reordered.map((item,menuOrder)=>({...item,menuOrder})); busy.value=true; error.value=null; try{emit("saved",await saveMappingConfiguration({...props.configuration,applicationBindings:bindings}))}catch(e){error.value=String(e)}finally{busy.value=false} }
</script>
<template><section class="card"><h2>应用绑定</h2><p v-if="!configuration.templates.length" class="muted">请先创建模板。</p><p v-if="error" class="error-text">{{error}}</p><div v-for="app in apps" :key="app.id" class="status-panel"><span><strong>{{app.name}}</strong><small>{{app.installed?'可用':'未安装或未找到'}}</small></span><select :disabled="busy||!configuration.templates.length" :value="binding(app.id)?.templateId??''" @change="bind(app.id,($event.target as HTMLSelectElement).value)"><option value="">未绑定</option><option v-for="t in configuration.templates" :key="t.id" :value="t.id">{{t.name}}</option></select><button v-if="binding(app.id)" class="secondary-button" @click="unbind(app.id)">解除</button></div><div v-for="(item,index) in orderedBindings()" :key="item.applicationId" class="button-row"><span>{{ apps.find(a=>a.id===item.applicationId)?.name ?? '自定义应用' }}</span><button class="secondary-button" :disabled="busy||index===0" @click="move(item.applicationId,-1)">上移</button><button class="secondary-button" :disabled="busy||index===orderedBindings().length-1" @click="move(item.applicationId,1)">下移</button></div><button type="button" class="secondary-button" @click="custom">添加应用</button></section></template>
