<script setup lang="ts">
import { ref } from "vue";
import { applyMappingConfigurationImport, exportMappingConfiguration, listPresetApps, previewMappingConfigurationImport, previewTemplateImport, type MappingConfiguration, type MappingConfigurationImportPreview, type TemplateImportPreview } from "../lib/bridge";
const props=defineProps<{ configuration: MappingConfiguration }>(); const emit = defineEmits<{ applied: [configuration: MappingConfiguration] }>();
const preview = ref<MappingConfigurationImportPreview | null>(null); const error=ref<string|null>(null); const busy=ref(false);
const selected=ref<string[]>([]); const sourceSelected=ref<string[]>([]); const names=ref<Record<string,string>>({}); const replaceBindings=ref(false); const append=ref<TemplateImportPreview|null>(null);
const applicationNames=ref<Record<string,string>>({});
void listPresetApps().then(items=>applicationNames.value=Object.fromEntries(items.map(item=>[item.id,item.name]))).catch(()=>{});
function applicationLabel(applicationId:string){return applicationNames.value[applicationId]??`未解析应用（${applicationId}）`}
async function exportAll(){busy.value=true;error.value=null;try{await exportMappingConfiguration(null)}catch(e){error.value=String(e)}finally{busy.value=false}}
async function choose(){busy.value=true;error.value=null;try{preview.value=await previewMappingConfigurationImport();sourceSelected.value=preview.value?.configuration.templates.map(x=>x.id)??[];names.value=Object.fromEntries((preview.value?.configuration.templates??[]).map(x=>[x.id,x.name]));append.value=null}catch(e){error.value=String(e)}finally{busy.value=false}}
async function apply(){if(!preview.value)return;busy.value=true;error.value=null;try{emit("applied",await applyMappingConfigurationImport(preview.value.token));preview.value=null}catch(e){error.value=String(e)}finally{busy.value=false}}
function clearAppend(){append.value=null}
async function previewAppend(){if(!preview.value?.sourceToken||!sourceSelected.value.length)return;busy.value=true;try{append.value=await previewTemplateImport(preview.value.sourceToken,{templateIds:sourceSelected.value,resolvedNames:names.value,replaceApplicationBindings:replaceBindings.value})}catch(e){error.value=String(e)}finally{busy.value=false}}
</script>
<template><section class="card"><h2>配置导入与导出</h2><div class="button-row"><button :disabled="busy" @click="exportAll">导出全部配置</button><button :disabled="busy||!selected.length" @click="exportMappingConfiguration(selected)">导出选中模板</button><button class="secondary-button" :disabled="busy" @click="choose">选择导入文件</button></div><label v-for="t in configuration.templates" :key="t.id"><input v-model="selected" type="checkbox" :value="t.id">{{t.name}}</label><p v-if="error" class="error-text">{{error}}</p><div v-if="preview" class="status-panel"><div><strong>导入预览 · 格式 v{{preview.formatVersion}}</strong><div v-if="preview.sourceToken"><label v-for="t in preview.configuration.templates" :key="t.id"><input v-model="sourceSelected" type="checkbox" :value="t.id" @change="clearAppend">{{t.name}} <input v-model="names[t.id]" @input="clearAppend"></label><label><input v-model="replaceBindings" type="checkbox" @change="clearAppend">替换同应用的现有绑定</label></div><div class="button-row"><button :disabled="busy" @click="apply">整包替换</button><button v-if="preview.sourceToken" :disabled="busy||!sourceSelected.length" @click="previewAppend">预览追加</button><button class="secondary-button" @click="preview=null">取消</button></div></div></div><div v-if="append" class="status-panel"><div><strong>追加预览</strong><small v-for="item in append.templates" :key="item.sourceTemplateId">{{item.template.name}}</small><small v-for="binding in append.addedApplicationBindings" :key="`added-${binding.applicationId}`">新增或更新绑定：{{applicationLabel(binding.applicationId)}}</small><small v-for="applicationId in append.replacedApplicationIds" :key="`replaced-${applicationId}`">将替换绑定：{{applicationLabel(applicationId)}}</small><small v-for="applicationId in append.skippedApplicationIds" :key="`skipped-${applicationId}`">将跳过绑定：{{applicationLabel(applicationId)}}</small><small v-for="applicationId in append.unresolvedApplicationIds" :key="`unresolved-${applicationId}`">未解析：{{applicationLabel(applicationId)}}</small><button :disabled="busy" @click="applyMappingConfigurationImport(append.token).then((x)=>emit('applied',x))">确认追加</button></div></div></section></template>
